### ISSUE TITLE
Missing groovyBC

### ISSUE THREAD

**Issue by MakisH** [precice/vm#23]
We need it for the Turek-Hron FSI3 benchmark case: https://precice.org/tutorials-turek-hron-fsi3.html

**Comment by MakisH** [comment]
swak4Foam is currently failing to build: https://github.com/precice/vm/runs/5133437246?check_suite_focus=true

I think I have seen something like this before. @DavidSCN do you maybe remember doing anything special when building on Ubuntu 20.04?

**Comment by DavidSCN** [comment]
As far as I remember I also had some issues building swak4foam completely. However, this was always after groovyBC was already completed, so that I did not really investigated this further. I'm not sure if that's the case here.

**Comment by MakisH** [comment]
I fixed this by installing swak4Foam from develop. Since I suspect this may break in the future, commit [ea7680cdcf8b](http://hg.code.sf.net/p/openfoam-extend/swak4Foam/rev/ea7680cdcf8b) seems to work with OpenFOAM v2112.

Since most people are not working with mercurial, some useful commands:
```
hg branch # find out the current branch
hg identify # find out the current commit
hg checkout develop # switch to the devleop branch
```

Here is also the error I got while building swak4Foam for OpenFOAM v2112 on Ubuntu 20.04 (hoping that it helps more people in the future):

```
    default: g++ -std=c++14 -m64 -pthread -DOPENFOAM=2112 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -Wno-unknown-pragmas  -O3  -DNoRepository -ftemplate-depth-100 -IMake/linux64GccDPInt32Opt  	 -I/usr/lib/openfoam/openfoam2112/src/finiteVolume/lnInclude -I/usr/lib/openfoam/openfoam2112/src/surfMesh/lnInclude -I/usr/lib/openfoam/openfoam2112/src/sampling/lnInclude -I/usr/lib/openfoam/openfoam2112/src/fileFormats/lnInclude  -I/usr/lib/openfoam/openfoam2112/src/dynamicMesh/lnInclude -I/usr/lib/openfoam/openfoam2112/src/lagrangian/basic/lnInclude -I/usr/lib/openfoam/openfoam2112/src/surfMesh/lnInclude -I/usr/lib/openfoam/openfoam2112/src/meshTools/lnInclude -I../filesThatAreOnlyInSomeDistributions/OutputFilerDropin/ -iquote. -IlnInclude -I/usr/lib/openfoam/openfoam2112/src/OpenFOAM/lnInclude -I/usr/lib/openfoam/openfoam2112/src/OSspecific/POSIX/lnInclude   -fPIC -c entryToExpression/entryToExpression.C -o Make/linux64GccDPInt32Opt/entryToExpression/entryToExpression.o
    default: entryToExpression/entryToExpression.C: In static member function ‘static Foam::autoPtr<Foam::entryToExpression> Foam::entryToExpression::New(const Foam::word&)’:
    default: entryToExpression/entryToExpression.C:55:5: error: ‘nothingConstructorTable’ is not a class, namespace, or enumeration
    default:    55 |     nothingConstructorTable::iterator cstrIter =
    default:       |     ^~~~~~~~~~~~~~~~~~~~~~~
    default: entryToExpression/entryToExpression.C:58:9: error: ‘cstrIter’ was not declared in this scope; did you mean ‘strstr’?
    default:    58 |     if (cstrIter == nothingConstructorTablePtr_->end())
    default:       |         ^~~~~~~~
    default:       |         strstr
    default: entryToExpression/entryToExpression.C:76:13: error: ‘cstrIter’ was not declared in this scope; did you mean ‘strstr’?
    default:    76 |             cstrIter()()
    default:       |             ^~~~~~~~
    default:       |             strstr
    default: make: *** [/usr/lib/openfoam/openfoam2112/wmake/rules/General/transform:35: Make/linux64GccDPInt32Opt/entryToExpression/entryToExpression.o] Error 1
    default: Parser library did not compile OK. No sense continuing as everything else depends on it
    default: 
    default: Requirements for Library not satisfied. I see no sense in going on
    default: Check the README before you go on to ask. And search: Most likely your problem occurred to 5 other people before and has been solved on the MessageBoard
```

The page [Understanding Error Messages](https://openfoamwiki.net/index.php/Installation/swak4Foam/Understanding_Error_Messages) may also help in similar situations.

**Comment by altaflone** [comment]
so, what is the solution here. been trying to install swak4foam for openfoam-v2112 on ubuntu 20.04. was not able to do it. can anyone tell simple steps to follow.

**Comment by MakisH** [comment]
@altaflone swak4foam is already installed in the VM. This is how we install it: https://github.com/precice/vm/blob/develop/provisioning/install-openfoam.sh#L22-L31 (commented-out, as we do it once and then reuse the binaries).

Note that I could also not make it build completely. It is always failing at some point with some error I don't understand, but it looks like it successfully builds groovyBC before that point. Check your `$FOAM_USER_LIBBIN`, maybe it is already there.

**Comment by altaflone** [comment]
Dear sir 

Thanks for your kind words of advice. i did follow the procedure as directed by you. the error message i get is pasted below. been trying this for a week. still have got no success.


This script is rather crude. If it doesn't work try the steps by hand. And be sure to run it from the root of the swak-installation (as ./maintainanceScripts/compileRequirements.sh). Otherwise it probably won't work

Bison already installed/compiled
Bison successfully compiled
Lua already installed/compiled
Lua successfully compiled

Add /home/altaf/OpenFOAM/altaf-v2112/swak4Foam/privateRequirements/bin to PATH-variable. The ./Allwmake-script will use this directory automatically

Current OpenFOAM version is v2112.
Previously compiled for OpenFOAM (v2112)

/home/altaf/OpenFOAM/altaf-v2112/swak4Foam/privateRequirements/bin existing. Prepending to PATH-variable (private version of Bison)

Reading variables from 'swakConfiguration'
Looking for Python 2
Found Python 2.7
Configuring Python 2.7
Using python2.7 at /usr/bin/python2.7-config for python2
Looking for Python 3
Found Python 3.8
Configuring Python 3.8
Using python3.8 at /usr/bin/python3.8-config for python3
Using our own Lua at /home/altaf/OpenFOAM/altaf-v2112/swak4Foam/privateRequirements
Checking swak4Foam-version and generating file
Swak version is 202x.yy.0
hg info: 481d96f16780 (develop) tip
Using /usr/bin/bear to build compilation database
Bison: /home/altaf/OpenFOAM/altaf-v2112/swak4Foam/privateRequirements/bin/bison
Flex: /usr/bin/flex
Bison at /home/altaf/OpenFOAM/altaf-v2112/swak4Foam/privateRequirements/bin/bison is version 3.4 (Major 3 Minor 4)
Flex is version 2.6.4 (Minor version: 4)
OpenFOAM-version: Major 2112 Minor 0 Patch 0 (-1 == x / 0) Fork: com
No change to swak4FoamParsers/foamVersion4swak.H

Please include the output above when reporting a problem in the compilation. It helps diagnosing the problem


wmake libso swak4FoamParsers
g++ -std=c++11 -m64 -pthread -DOPENFOAM=2112 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -Wno-unknown-pragmas  -O3  -DNoRepository -ftemplate-depth-100 -IMake/linux64GccDPInt32Opt         -I/home/altaf/foam-2112/OpenFOAM-v2112/src/finiteVolume/lnInclude -I/home/altaf/foam-2112/OpenFOAM-v2112/src/surfMesh/lnInclude -I/home/altaf/foam-2112/OpenFOAM-v2112/src/sampling/lnInclude -I/home/altaf/foam-2112/OpenFOAM-v2112/src/fileFormats/lnInclude  -I/home/altaf/foam-2112/OpenFOAM-v2112/src/dynamicMesh/lnInclude -I/home/altaf/foam-2112/OpenFOAM-v2112/src/lagrangian/basic/lnInclude -I/home/altaf/foam-2112/OpenFOAM-v2112/src/surfMesh/lnInclude -I/home/altaf/foam-2112/OpenFOAM-v2112/src/meshTools/lnInclude -I../filesThatAreOnlyInSomeDistributions/OutputFilerDropin/ -iquote. -IlnInclude -I/home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude -I/home/altaf/foam-2112/OpenFOAM-v2112/src/OSspecific/POSIX/lnInclude   -fPIC -c repositories/SetsRepository.C -o Make/linux64GccDPInt32Opt/repositories/SetsRepository.o
repositories/SetsRepository.C:48:22: error: ‘scalar’ was not declared in this scope; did you mean ‘Foam::scalar’?
   48 | typedef Foam::writer<scalar> writerType;
      |                      ^~~~~~
      |                      Foam::scalar
In file included from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/floatScalar.H:41,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/scalar.H:42,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/IOstream.H:52,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/Ostream.H:42,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/OSstream.H:42,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/messageStream.H:285,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/error.H:59,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/autoPtrI.H:29,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/autoPtr.H:312,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/List.H:46,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/labelList.H:45,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/UPstream.H:46,
                 from /home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/Pstream.H:45,
                 from lnInclude/DebugOStream.H:50,
                 from lnInclude/swak.H:880,
                 from repositories/SetsRepository.C:33:
/home/altaf/foam-2112/OpenFOAM-v2112/src/OpenFOAM/lnInclude/scalarFwd.H:63:22: note: ‘Foam::scalar’ declared here
   63 | typedef doubleScalar scalar;
      |                      ^~~~~~
repositories/SetsRepository.C:48:28: error: template argument 1 is invalid
   48 | typedef Foam::writer<scalar> writerType;
      |                            ^
repositories/SetsRepository.C: In member function ‘Foam::sampledSet& Foam::SetsRepository::getSet(const Foam::dictionary&, const Foam::polyMesh&)’:
repositories/SetsRepository.C:182:32: error: expected unqualified-id before ‘(’ token
  182 |                 writerType::New(format)
      |                                ^
repositories/SetsRepository.C:182:32: error: expected ‘)’ before ‘(’ token
  182 |                 writerType::New(format)
      |                                ^
      |                                )
repositories/SetsRepository.C:181:42: note: to match this ‘(’
  181 |             autoPtr<writerType> theWriter(
      |                                          ^
repositories/SetsRepository.C:182:39: warning: declaration of ‘Foam::autoPtr<int> Foam::theWriter(...)’ has ‘extern’ and is initialized
  182 |                 writerType::New(format)
      |                                       ^
repositories/SetsRepository.C:182:32: error: initializer provided for function
  182 |                 writerType::New(format)
      |                                ^
repositories/SetsRepository.C:201:43: error: request for member ‘getFileName’ in ‘* Foam::theWriter’, which is of non-class type ‘Foam::autoPtr<int>(...)’
  201 |                 fileName fName(theWriter->getFileName(set, wordList(0)));
      |                                           ^~~~~~~~~~~
repositories/SetsRepository.C:207:28: error: request for member ‘write’ in ‘* Foam::theWriter’, which is of non-class type ‘Foam::autoPtr<int>(...)’
  207 |                 theWriter->write(
      |                            ^~~~~
repositories/SetsRepository.C: In member function ‘virtual bool Foam::SetsRepository::writeData(Foam::Ostream&) const’:
repositories/SetsRepository.C:278:28: error: expected unqualified-id before ‘(’ token
  278 |             writerType::New(format)
      |                            ^
repositories/SetsRepository.C:278:28: error: expected ‘)’ before ‘(’ token
  278 |             writerType::New(format)
      |                            ^
      |                            )
repositories/SetsRepository.C:277:38: note: to match this ‘(’
  277 |         autoPtr<writerType> theWriter(
      |                                      ^
repositories/SetsRepository.C:278:35: warning: declaration of ‘Foam::autoPtr<int> Foam::theWriter(...)’ has ‘extern’ and is initialized
  278 |             writerType::New(format)
      |                                   ^
repositories/SetsRepository.C:278:28: error: initializer provided for function
  278 |             writerType::New(format)
      |                            ^
repositories/SetsRepository.C:288:35: error: request for member ‘getFileName’ in ‘* Foam::theWriter’, which is of non-class type ‘Foam::autoPtr<int>(...)’
  288 |         fileName fName(theWriter->getFileName(set, wordList(0)));
      |                                   ^~~~~~~~~~~
repositories/SetsRepository.C:291:20: error: request for member ‘write’ in ‘* Foam::theWriter’, which is of non-class type ‘Foam::autoPtr<int>(...)’
  291 |         theWriter->write(
      |                    ^~~~~
repositories/SetsRepository.C:273:21: warning: unused variable ‘format’ [-Wunused-variable]
  273 |         const word &format=it();
      |                     ^~~~~~
make: *** [/home/altaf/foam-2112/OpenFOAM-v2112/wmake/rules/General/transform:35: Make/linux64GccDPInt32Opt/repositories/SetsRepository.o] Error 1
Parser library did not compile OK. No sense continuing as everything else depends on it

Requirements for Library not satisfied. I see no sense in going on
Check the README before you go on to ask. And search: Most likely your problem occurred to 5 other people before and has been solved on the MessageBoard


                                 *****************************

Thank you sir

altaf

**Comment by MakisH** [comment]
Did you try out this part?

> Note that I could also not make it build completely. It is always failing at some point with some error I don't understand, but it looks like it successfully builds groovyBC before that point. Check your `$FOAM_USER_LIBBIN`, maybe it is already there.

What does `ls $FOAM_USER_LIBBIN` show you?

Note that this generally is an issue of swak4Foam, not of preCICE.
